# Regenerates Public_html/assets/images/Landing/landing-images.js
# from the files in that folder. Run after adding or removing photos:
#   pwsh -File scripts/sync-landing-images.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dir  = Join-Path $root 'Public_html\assets\images\Landing'

if (-not (Test-Path $dir)) {
    Write-Error "Landing folder not found: $dir"
    exit 1
}

$ext   = @('.jpg', '.jpeg', '.png', '.gif', '.webp', '.avif')
$files = Get-ChildItem -LiteralPath $dir -File |
    Where-Object { $ext -contains $_.Extension.ToLower() } |
    Sort-Object { $_.Name }

$lines = @($files | ForEach-Object { "  `"assets/images/Landing/$($_.Name)`"" })
$content = @"
/* Auto-generated by scripts/sync-landing-images -- do not edit manually */
window.LANDING_IMAGES = [
$($lines -join ",`n")
];
"@

$out = Join-Path $dir 'landing-images.js'
Set-Content -LiteralPath $out -Value $content -Encoding utf8
Write-Host "Wrote $($files.Count) paths to landing-images.js"
